apiVersion: apps/v1
kind: Deployment
metadata:
  name: fasdswc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fasdswc
  template:
    metadata:
      labels:
        app: fasdswc
    spec:
      containers:
      - image: okteto.dev/fasdswc:latest
        name: fasdswc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4fcc108c-6b5f-4104-930f-ebc5ac62c825"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "4fcc108c-6b5f-4104-930f-ebc5ac62c825"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
